// Generated by CoffeeScript 1.3.3
var CSClassGame, EJClassGame,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

enchant();

CSClassGame = (function(_super) {

  __extends(CSClassGame, _super);

  function CSClassGame() {
    CSClassGame.__super__.constructor.call(this, 320, 240);
    this.fps = 24;
    this.preload('chara1.gif');
    this.onload = function() {
      var bear, game;
      bear = new Sprite(32, 32);
      bear.x = 8;
      bear.y = 8;
      bear.image = this.assets['chara1.gif'];
      game = this;
      bear.addEventListener(Event.ENTER_FRAME, function() {
        if (game.input.right) {
          bear.x += 2;
        }
        if (game.input.left) {
          bear.x -= 2;
        }
        if (game.input.up) {
          bear.y -= 2;
        }
        if (game.input.down) {
          bear.y += 2;
        }
      });
      this.rootScene.addChild(bear);
    };
    this.start();
    return;
  }

  return CSClassGame;

})(Game);

EJClassGame = Class.create(Game, {
  initialize: function() {
    Game.call(this, 320, 240);
    this.fps = 24;
    this.preload('chara1.gif');
    this.onload = function() {
      var bear, game;
      bear = new Sprite(32, 32);
      bear.x = 8;
      bear.y = 8;
      bear.image = this.assets['chara1.gif'];
      game = this;
      bear.addEventListener(Event.ENTER_FRAME, function() {
        if (game.input.right) {
          bear.x += 2;
        }
        if (game.input.left) {
          bear.x -= 2;
        }
        if (game.input.up) {
          bear.y -= 2;
        }
        if (game.input.down) {
          bear.y += 2;
        }
      });
      this.rootScene.addChild(bear);
    };
    this.start();
  }
});

window.onload = function() {
  return new CSClassGame;
};
